# Server
[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = uI7Cz/m5vkAi/ZULM+ZT6GVn+LGXe1BEtV+Cr30q01k=
PostUp = sh -c "iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE"
PostDown = sh -c "iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE"
Table = auto
MTU = 1420

# LAN2
[Peer]
PublicKey = EPNpnVXNxJwEWI+1vwUnzVJTQQl+oQ0YAuG+0vx+z1I=
PresharedKey = ZhRXFRbdlCKG1g9Vo7a7Y8iq9KoXcfJYrQzhP+HkOUY=
AllowedIPs = 10.0.0.2/32,192.168.2.0/24

# LAN3
[Peer]
PublicKey = lCcFgctZVtA4pfxZPUENuN+WcXu+v/71+ingZbXDr1M=
PresharedKey = vUUP8K7RaUWhsgAehj0vSi2Sa6aEWrSPrEpeKEJTzKI=
AllowedIPs = 10.0.0.3/32,192.168.3.0/24
