[Interface]
Address = 10.0.0.3/24
PrivateKey = GJEa7+9SyeELkvE1aOI5y+Qbzhskmm5rbNxUOcCF1E4=
PostUp = /root/routing.sh
MTU = 1420

[Peer]
PublicKey = 2QwWlAUY7eVeN49dXDoIdn7mDdM/Ujx8wjy1Lh/Fcl4=
PresharedKey = vUUP8K7RaUWhsgAehj0vSi2Sa6aEWrSPrEpeKEJTzKI=
AllowedIPs = 10.0.0.0/24,192.168.1.0/24
Endpoint = 30.35.40.45:51820
PersistentKeepalive = 15
